# Generated by Django 3.0.6 on 2020-05-11 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Number', models.CharField(max_length=10)),
                ('Withdrawal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Deposit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Image', models.ImageField(upload_to='media/transaction_img')),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Comment', models.CharField(max_length=255)),
                ('created_by', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_settings.Account', verbose_name='Bank Account')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_settings.Category', verbose_name='Bank Account')),
            ],
        ),
    ]
