# Generated by Django 3.0.6 on 2020-05-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='Name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
