# Generated by Django 3.0.6 on 2020-05-12 13:31

import budget_settings.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_settings', '0002_auto_20200511_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_settings.Category', verbose_name='Category Account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Comment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Image',
            field=models.ImageField(blank=True, upload_to='media/transaction_img'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Number',
            field=models.CharField(blank=True, default=budget_settings.models.increment_transaction_number, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Withdrawal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
    ]
