# Generated by Django 3.0.6 on 2020-05-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_settings', '0003_auto_20200512_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='media/transaction_img'),
        ),
    ]
