# Generated by Django 3.0.6 on 2020-05-13 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_settings', '0005_auto_20200512_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='Image',
        ),
        migrations.CreateModel(
            name='TransactionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='transaction_img/')),
                ('Transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_settings.Transaction', verbose_name='Transaction')),
            ],
        ),
    ]
