# Generated by Django 3.0.6 on 2020-05-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_settings', '0006_auto_20200513_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='media/transaction_img'),
        ),
        migrations.DeleteModel(
            name='TransactionImage',
        ),
    ]
